// W275.C — drift guard for apps/docs /api index page. Pins the
// OpenAPI URL claim to the canonical host so the docs entry-point
// matches what the running server actually serves.

import { readFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, resolve } from 'node:path';
import { describe, expect, it } from 'vitest';

const HERE = dirname(fileURLToPath(import.meta.url));
const REPO_ROOT = resolve(HERE, '..', '..', '..', '..');
const PAGE = resolve(REPO_ROOT, 'apps/docs/src/pages/api/index.astro');
const OPENAPI = resolve(REPO_ROOT, 'apps/server/src/lib/openapi.ts');

function read(p: string): string {
  return readFileSync(p, 'utf8');
}

describe('W275.C docs /api index ↔ live OpenAPI parity', () => {
  const page = read(PAGE);
  const lib = read(OPENAPI);

  it('cites the live OpenAPI URL', () => {
    expect(page).toMatch(/api\.driftstack\.dev\/openapi\.json/);
  });

  it('OpenAPI is actually generated by the server (route is wired in lib/openapi.ts)', () => {
    // openapi.ts must mention the .json suffix to confirm the route
    // contract — drift would be e.g. switching to .yaml only.
    expect(lib).toMatch(/openapi\.json|json/i);
  });

  it('does not cite the legacy api.driftstack.dev/errors/ URI form', () => {
    expect(page).not.toMatch(/api\.driftstack\.dev\/errors\//);
  });
});
