// Proxy-accuracy audit §5 — the test matrix, native vantage (L1 → L5).
//
// `tests/fixtures/native-socks5-probe-matrix.json` is GENERATED by `cargo test`
// in src-tauri (socks5_probe.rs): each §5.2 fixture is a fake SOCKS5 proxy on
// 127.0.0.1 that LOGS what really happened — connections accepted and turned
// away, each login, each CONNECT and any bytes after its reply, each UDP
// ASSOCIATE and its refusal, datagrams in and out — beside what the REAL native
// probe returned against it. The Rust test fails when the probe stops matching
// the file, so this suite always reads what the shipped probe does.
//
// Here every fixture's result goes through the app's own derivations and chips,
// and each mark is tied to that log (contract C1): a ✓ needs the positive event
// in the log, a ⤵ needs a logged refusal, anything else is — (or ~, and only
// where §4 allows it). Then the §5.2 row's expected badges, fixture by fixture.

import { readFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { afterEach, describe, expect, it } from 'vitest';
import { cleanup, render } from '@testing-library/react';
import { proxyCapabilities, ProxyCapabilityChips } from '../../src/components/ProxyCapabilities';
import { capabilityChips, type CapsInput } from '../../src/components/ProfilePhoneCard';
import { listUdpVerdict } from '../../src/components/ProfilesTable';
import { rowShowsUdpAndQuic } from '../../src/views/ProxiesView';
import { isProxyUsable, proxyVerdict, type ProxyTestResult } from '../../src/lib/proxies';

afterEach(cleanup);

interface FixtureLog {
  tcp_accepted: number;
  tcp_turned_away: number;
  logins: Array<[string, string]>;
  connects: number;
  connect_refused: number;
  bytes_after_connect_reply: number;
  associates: number;
  associate_refused: number;
  datagrams_in: number;
  datagrams_out: number;
}
interface Fixture {
  fixture: string;
  what_really_happens: string;
  log: FixtureLog;
  result: Omit<ProxyTestResult, 'latency_ms'>;
}

const HERE = dirname(fileURLToPath(import.meta.url));
const MATRIX = JSON.parse(
  readFileSync(resolve(HERE, '..', 'fixtures', 'native-socks5-probe-matrix.json'), 'utf8'),
) as { fixtures: Fixture[] };
const byId = new Map(MATRIX.fixtures.map((f) => [f.fixture, f]));
const resultOf = (f: Fixture): ProxyTestResult => ({ ...f.result, latency_ms: 20 });

/** The marks the Proxies tab draws for this result: UDP chip and QUIC chip. */
function tabMarks(r: ProxyTestResult): { udp: string; quic: string } {
  const { container } = render(<ProxyCapabilityChips result={r} />);
  const text = (key: string): string =>
    (container.querySelector(`[data-capability="${key}"]`)?.textContent ?? '').trim();
  const marks = { udp: text('webrtc'), quic: text('quic') };
  cleanup();
  return marks;
}

describe('§5 matrix — the golden file covers the fixtures stage 1 needs', () => {
  it('holds A, B, B0, C7, C2, D, H, J, K, L and M, each with a log', () => {
    expect([...byId.keys()].sort()).toEqual(
      ['A', 'B', 'B0', 'C2', 'C7', 'D', 'H', 'J', 'K', 'L', 'M'].sort(),
    );
    for (const f of MATRIX.fixtures) expect(f.log.tcp_accepted, f.fixture).toBeGreaterThan(0);
  });
});

describe('C1 — every UDP mark on every surface is backed by the fixture’s log', () => {
  for (const f of MATRIX.fixtures) {
    it(`${f.fixture} (${f.what_really_happens})`, () => {
      const r = resultOf(f);
      const caps = proxyCapabilities(r);
      const udp = caps.find((c) => c.key === 'webrtc');
      const quic = caps.find((c) => c.key === 'quic');
      const relayed = f.log.datagrams_in >= 1 && f.log.datagrams_out >= 1;
      const refused = f.log.associate_refused >= 1;
      const usable = isProxyUsable(r);

      // ✓ UDP ⇔ a datagram went through the fake's relay AND came back.
      expect(udp?.ok === true && udp.unmeasured !== true, 'a ✓ needs a round trip in the log').toBe(
        usable && relayed,
      );
      // ⤵ UDP ⇔ the fake logged a refusal of the UDP request.
      const fallsBack = udp?.ok === false && udp.unmeasured !== true;
      expect(fallsBack, 'a ⤵ needs a logged refusal').toBe(usable && refused);
      // …anything else is "— UDP".
      if (!(usable && (relayed || refused))) expect(udp?.unmeasured).toBe(true);

      // C4 — "~ QUIC" only from a relay that answered; never from a grant.
      if (quic?.inferred === true) expect(relayed).toBe(true);
      // The header's UDP + QUIC tally, with a measured QUIC beside it.
      expect(rowShowsUdpAndQuic({ scheme: 'socks5' }, r, undefined, undefined, true)).toBe(
        usable && relayed,
      );

      // The same state on the card and the list.
      const cardUdp = capabilityChips({
        hasProxy: true,
        capabilities: r,
      } as CapsInput).eligible.find((c) => c.key === 'udp');
      const list = listUdpVerdict(caps, undefined);
      if (usable && relayed) {
        expect(cardUdp?.text).toBe('✓ UDP');
        expect(list).toBe('ok');
      } else if (usable && refused) {
        expect(cardUdp?.text).toBe('⤵ UDP');
        expect(list).toBe('fail');
      } else {
        expect(list).toBe('unknown');
      }

      // Reachability is never a fact our own second connection invented: a fake
      // that accepted and CONNECTed reads reachable.
      if (f.log.connects >= 1) expect(r.reachable).toBe(true);
      // Nothing is ever written into a tunnel or onto a refused stream.
      expect(f.log.bytes_after_connect_reply).toBe(0);
    });
  }
});

describe('§5.2 — the expected badges, fixture by fixture', () => {
  const marks = (id: string): { udp: string; quic: string } => {
    const f = byId.get(id);
    if (f === undefined) throw new Error(`no fixture ${id}`);
    return tabMarks(resultOf(f));
  };

  it('A relay-all and B0 (BND 0.0.0.0): ✓ UDP, ~ QUIC, healthy', () => {
    for (const id of ['A', 'B0']) {
      expect(marks(id)).toEqual({ udp: '✓UDP', quic: '~QUIC' });
      expect(proxyVerdict(resultOf(byId.get(id)!)).ok).toBe(true);
    }
  });

  it('B grant-drop: "— UDP · not verified", no "~ QUIC", and not counted in the tally', () => {
    const m = marks('B');
    expect(m.udp).toBe('—UDP · not verified');
    expect(m.quic).not.toContain('~');
    expect(m.quic).not.toContain('⤵');
  });

  it('C7 / C2 refusals: ⤵ UDP ⤵ QUIC — the only measured NO', () => {
    for (const id of ['C7', 'C2']) expect(marks(id)).toEqual({ udp: '⤵UDP', quic: '⤵QUIC' });
  });

  it('D wrong password: "Auth failed", and the chips are not measured', () => {
    const r = resultOf(byId.get('D')!);
    expect(proxyVerdict(r).label).toBe('Auth failed');
    expect(marks('D')).toEqual({ udp: '—UDP', quic: '—QUIC' });
  });

  it('H login ok, CONNECT refused: "Cannot route", UDP never asked (— not ⤵)', () => {
    const f = byId.get('H')!;
    expect(proxyVerdict(resultOf(f)).label).toBe('Cannot route');
    expect(f.log.associates).toBe(0);
    expect(marks('H').udp).toBe('—UDP');
  });

  it('J one connection at a time and K slow second greeting: healthy, never "unreachable"; UDP not measured', () => {
    for (const id of ['J', 'K']) {
      const r = resultOf(byId.get(id)!);
      expect(proxyVerdict(r).ok, id).toBe(true);
      expect(marks(id).udp, id).toBe('—UDP');
    }
    expect(byId.get('J')!.log.tcp_turned_away).toBe(1);
  });

  it('L CONNECT slower than the wait: not usable, but never "will not carry traffic"; nothing written into the tunnel', () => {
    const f = byId.get('L')!;
    expect(isProxyUsable(resultOf(f))).toBe(false);
    expect(f.result.message).not.toContain('will not carry traffic');
    expect(f.result.message).toContain('did not answer');
    expect(f.log.associates).toBe(0);
  });

  it('M username with no password: logs in as ("u", "") on both connections, and UDP relays', () => {
    const f = byId.get('M')!;
    expect(f.log.logins).toEqual([
      ['u', ''],
      ['u', ''],
    ]);
    expect(marks('M').udp).toBe('✓UDP');
  });
});
