"""Codegen output. Regenerated by ``scripts/generate.sh``.

Hand-edit nothing in this package — it gets clobbered every regeneration.
Customer-facing types are re-exported from :mod:`driftstack` (the package
root); to add a wrapping layer, edit there.
"""
