# generated by datamodel-codegen:
#   filename:  openapi.json
#   timestamp: 2026-07-13T10:57:50+00:00

from __future__ import annotations

from typing import Any, Literal
from uuid import UUID

from pydantic import (
    AnyUrl,
    AwareDatetime,
    BaseModel,
    EmailStr,
    Field,
    PositiveInt,
    RootModel,
    conint,
    constr,
)


class Account(BaseModel):
    id: constr(
        pattern=r"^acc_[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$"
    )
    email: EmailStr
    name: str | None
    tier: Literal[
        "free",
        "solo_manual",
        "team_manual",
        "agency_manual",
        "api_starter",
        "api_builder",
        "api_scale",
        "enterprise",
    ]
    status: Literal["active", "suspended", "deleted"]
    created_at: AwareDatetime
    """
    ISO 8601 timestamp with timezone offset, e.g. 2026-05-02T09:15:00Z
    """
    updated_at: AwareDatetime
    """
    ISO 8601 timestamp with timezone offset, e.g. 2026-05-02T09:15:00Z
    """


class Team(BaseModel):
    owner_account_id: str
    owner_email: str
    owner_name: str | None
    role: Literal["admin", "member"]
    membership_id: str


class AccountMeResponse(BaseModel):
    id: str
    email: EmailStr
    name: str | None
    tier: Literal[
        "free",
        "solo_manual",
        "team_manual",
        "agency_manual",
        "api_starter",
        "api_builder",
        "api_scale",
        "enterprise",
    ]
    status: Literal["active", "suspended", "deleted"]
    timezone: str | None
    slug: str | None
    region: Literal["us", "eu", "apac"] | None
    avatar_url: str | None
    avatar_source: Literal["user", "idp", "none"]
    mfa_enrolled: bool
    concurrent_session_cap: conint(ge=0)
    concurrent_session_active: conint(ge=0)
    profile_cap: conint(ge=0) | None
    profile_count: conint(ge=0)
    teams: list[Team]


class UpdateAccountMeRequest(BaseModel):
    name: constr(min_length=1, max_length=120) | None = None
    timezone: constr(min_length=1, max_length=64) | None = None
    slug: (
        constr(
            pattern=r"^[a-z0-9](?:[a-z0-9-]*[a-z0-9])?$", min_length=3, max_length=32
        )
        | None
    ) = None
    region: Literal["us", "eu", "apac"] | None = None


class ApiKey(BaseModel):
    id: constr(
        pattern=r"^key_[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$"
    )
    name: str
    key_prefix: str
    scopes: list[
        Literal[
            "read",
            "write",
            "admin",
            "account_owner",
            "driftstack_internal_admin",
            "gui_control",
            "read:sessions",
            "write:sessions",
            "read:profiles",
            "write:profiles",
            "admin:profiles",
            "read:webhooks",
            "write:webhooks",
            "admin:webhooks",
            "read:api-keys",
            "admin:api-keys",
            "read:billing",
            "admin:billing",
            "read:audit",
        ]
    ]
    last_used_at: AwareDatetime | None
    """
    ISO 8601 timestamp with timezone offset, e.g. 2026-05-02T09:15:00Z
    """
    revoked_at: AwareDatetime | None
    """
    ISO 8601 timestamp with timezone offset, e.g. 2026-05-02T09:15:00Z
    """
    expires_at: AwareDatetime | None
    """
    ISO 8601 timestamp with timezone offset, e.g. 2026-05-02T09:15:00Z
    """
    created_at: AwareDatetime
    """
    ISO 8601 timestamp with timezone offset, e.g. 2026-05-02T09:15:00Z
    """


class EgressCapabilities(BaseModel):
    udp_associate: bool
    quic_route: Literal["proxy", "direct", "disabled"]
    dns_remote_resolve: bool
    warnings: list[str] | None = []


class Session(BaseModel):
    id: constr(
        pattern=r"^ses_[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$"
    )
    account_id: constr(
        pattern=r"^acc_[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$"
    )
    api_key_id: constr(
        pattern=r"^key_[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$"
    )
    status: Literal["creating", "ready", "busy", "destroyed", "errored"]
    archetype: constr(pattern=r"^[a-z0-9_]+$", min_length=3, max_length=60)
    purpose: Literal[
        "production_customer", "cumulative_rig_validation", "test_domain_probe"
    ]
    label: str | None
    metadata: dict[str, Any] | None
    egress_capabilities: EgressCapabilities | None
    egress_capability_report: dict[str, Any] | None
    created_at: AwareDatetime
    """
    ISO 8601 timestamp with timezone offset, e.g. 2026-05-02T09:15:00Z
    """
    updated_at: AwareDatetime
    """
    ISO 8601 timestamp with timezone offset, e.g. 2026-05-02T09:15:00Z
    """
    last_state_at: AwareDatetime | None
    """
    ISO 8601 timestamp with timezone offset, e.g. 2026-05-02T09:15:00Z
    """
    destroyed_at: AwareDatetime | None
    """
    ISO 8601 timestamp with timezone offset, e.g. 2026-05-02T09:15:00Z
    """


class PairModeState(BaseModel):
    kind: str


class Livekit(BaseModel):
    ws_url: AnyUrl
    room: str
    token: str
    participant_identity: str
    expires_at: str


class Liveness(BaseModel):
    state: Literal["active", "provisioning", "idle", "terminating"] | None
    fresh: bool


class CapabilityReport(BaseModel):
    timestamp: str
    manual_input_available: bool | None
    streaming_state: Literal["provisioning", "live", "blank", "failed"] | None
    egress_state: Literal["live", "dead_proxy"] | None
    proxy_kind: Literal["socks5", "openvpn", "wireguard"]
    proxy_udp_supported: bool
    transport_mode_requested: Literal["h2-only", "h2-and-h3"]
    transport_mode_active: Literal["h2-only", "h2-and-h3"]
    safeguards_passed: bool


class ErrorEvent(BaseModel):
    timestamp: constr(min_length=1, max_length=64)
    code: constr(pattern=r"^[a-z][a-z0-9_]{0,127}$")
    severity: Literal["info", "warn", "error", "fatal"]
    summary: constr(max_length=4096)
    detail: constr(max_length=16384) | None
    customer_actionable: bool
    retryable: bool


class AgentSession(BaseModel):
    id: str
    account_id: str
    driftstack_session_id: str | None
    status: str
    closed_reason: str | None
    token_budget_total: int
    token_budget_remaining: int
    transcript_length: int
    closed_at: str | None
    created_by_user_id: str | None
    mode: Literal["manual", "ai", "pair"]
    model: Literal[
        "claude-opus-4-8", "claude-opus-4-7", "claude-sonnet-4-6", "claude-haiku-4-5"
    ]
    pair_mode_state: PairModeState | None
    created_at: str
    updated_at: str
    livekit: Livekit | None = None
    liveness: Liveness | None = None
    capability_report: CapabilityReport | None = None
    error_event: ErrorEvent | None = None


class AgentIntent1(BaseModel):
    kind: Literal["navigate"]
    url: str


class AgentIntent2(BaseModel):
    kind: Literal["interact"]
    action: Literal["tap", "type", "scroll", "swipe", "press"]
    selector: str | None = None
    value: str | None = None
    sensitive: bool | None = None


class AgentIntent3(BaseModel):
    kind: Literal["wait"]
    condition: Literal["idle", "selector_visible"]
    selector: str | None = None
    timeoutMs: conint(ge=0) | None = None


class AgentIntent4(BaseModel):
    kind: Literal["capture"]
    capture: Literal["screenshot", "dom_snapshot", "pdf"]


class AgentIntent5(BaseModel):
    kind: Literal["scroll"]
    direction: Literal["up", "down"]
    amount_px: PositiveInt | None = None


class AgentIntent6(BaseModel):
    kind: Literal["behavioral_pause"]
    duration_ms: conint(ge=0) | None = None
    reading_word_count: conint(ge=0) | None = None


class AgentIntent(
    RootModel[
        AgentIntent1
        | AgentIntent2
        | AgentIntent3
        | AgentIntent4
        | AgentIntent5
        | AgentIntent6
    ]
):
    root: (
        AgentIntent1
        | AgentIntent2
        | AgentIntent3
        | AgentIntent4
        | AgentIntent5
        | AgentIntent6
    )


class Intent(BaseModel):
    kind: Literal["navigate"]
    url: str


class Intent1(BaseModel):
    kind: Literal["interact"]
    action: Literal["tap", "type", "scroll", "swipe", "press"]
    selector: str | None = None
    value: str | None = None
    sensitive: bool | None = None


class Intent2(BaseModel):
    kind: Literal["wait"]
    condition: Literal["idle", "selector_visible"]
    selector: str | None = None
    timeoutMs: conint(ge=0) | None = None


class Intent3(BaseModel):
    kind: Literal["capture"]
    capture: Literal["screenshot", "dom_snapshot", "pdf"]


class Intent4(BaseModel):
    kind: Literal["scroll"]
    direction: Literal["up", "down"]
    amount_px: PositiveInt | None = None


class Intent5(BaseModel):
    kind: Literal["behavioral_pause"]
    duration_ms: conint(ge=0) | None = None
    reading_word_count: conint(ge=0) | None = None


class IntentResult1(BaseModel):
    kind: Literal["success"]
    intent: Intent | Intent1 | Intent2 | Intent3 | Intent4 | Intent5
    summary: str
    captureId: str | None = None


class Intent6(BaseModel):
    kind: Literal["navigate"]
    url: str


class Intent7(BaseModel):
    kind: Literal["interact"]
    action: Literal["tap", "type", "scroll", "swipe", "press"]
    selector: str | None = None
    value: str | None = None
    sensitive: bool | None = None


class Intent8(BaseModel):
    kind: Literal["wait"]
    condition: Literal["idle", "selector_visible"]
    selector: str | None = None
    timeoutMs: conint(ge=0) | None = None


class Intent9(BaseModel):
    kind: Literal["capture"]
    capture: Literal["screenshot", "dom_snapshot", "pdf"]


class Intent10(BaseModel):
    kind: Literal["scroll"]
    direction: Literal["up", "down"]
    amount_px: PositiveInt | None = None


class Intent11(BaseModel):
    kind: Literal["behavioral_pause"]
    duration_ms: conint(ge=0) | None = None
    reading_word_count: conint(ge=0) | None = None


class Diagnosis(BaseModel):
    category: Literal[
        "element_not_found",
        "page_load_failed",
        "condition_not_met",
        "capture_failed",
        "scroll_failed",
        "session_error",
        "invalid_request",
        "result_too_large",
        "unknown",
    ]
    retryable: bool


class IntentResult2(BaseModel):
    kind: Literal["failure"]
    intent: Intent6 | Intent7 | Intent8 | Intent9 | Intent10 | Intent11
    reason: str
    diagnosis: Diagnosis | None = None


class Intent12(BaseModel):
    kind: Literal["navigate"]
    url: str


class Intent13(BaseModel):
    kind: Literal["interact"]
    action: Literal["tap", "type", "scroll", "swipe", "press"]
    selector: str | None = None
    value: str | None = None
    sensitive: bool | None = None


class Intent14(BaseModel):
    kind: Literal["wait"]
    condition: Literal["idle", "selector_visible"]
    selector: str | None = None
    timeoutMs: conint(ge=0) | None = None


class Intent15(BaseModel):
    kind: Literal["capture"]
    capture: Literal["screenshot", "dom_snapshot", "pdf"]


class Intent16(BaseModel):
    kind: Literal["scroll"]
    direction: Literal["up", "down"]
    amount_px: PositiveInt | None = None


class Intent17(BaseModel):
    kind: Literal["behavioral_pause"]
    duration_ms: conint(ge=0) | None = None
    reading_word_count: conint(ge=0) | None = None


class IntentResult3(BaseModel):
    kind: Literal["confirmation_required"]
    intent: Intent12 | Intent13 | Intent14 | Intent15 | Intent16 | Intent17
    category: Literal["purchase", "payment", "account_deletion"]
    matchedText: str


class IntentResult(RootModel[IntentResult1 | IntentResult2 | IntentResult3]):
    root: IntentResult1 | IntentResult2 | IntentResult3


class Recipe(BaseModel):
    id: str
    account_id: str
    agent_session_id: str | None
    label: str
    description: str | None
    intent_count: int
    created_at: str
    updated_at: str


class IntentLog(BaseModel):
    kind: Literal["navigate"]
    url: str


class IntentLog1(BaseModel):
    kind: Literal["interact"]
    action: Literal["tap", "type", "scroll", "swipe", "press"]
    selector: str | None = None
    value: str | None = None
    sensitive: bool | None = None


class IntentLog2(BaseModel):
    kind: Literal["wait"]
    condition: Literal["idle", "selector_visible"]
    selector: str | None = None
    timeoutMs: conint(ge=0) | None = None


class IntentLog3(BaseModel):
    kind: Literal["capture"]
    capture: Literal["screenshot", "dom_snapshot", "pdf"]


class IntentLog4(BaseModel):
    kind: Literal["scroll"]
    direction: Literal["up", "down"]
    amount_px: PositiveInt | None = None


class IntentLog5(BaseModel):
    kind: Literal["behavioral_pause"]
    duration_ms: conint(ge=0) | None = None
    reading_word_count: conint(ge=0) | None = None


class RecipeDetail(BaseModel):
    id: str
    account_id: str
    agent_session_id: str | None
    label: str
    description: str | None
    intent_count: int
    created_at: str
    updated_at: str
    intent_log: list[
        IntentLog | IntentLog1 | IntentLog2 | IntentLog3 | IntentLog4 | IntentLog5
    ]


class Error(BaseModel):
    kind: Literal["http", "tls", "dns", "net", "timeout"]
    http_status: conint(ge=100, le=599) | None = None
    message: constr(max_length=500)


class PageState(BaseModel):
    state: Literal["loading", "loaded", "errored"]
    error: Error | None = None


class SessionState(BaseModel):
    url: AnyUrl | None
    title: str | None
    cookies: list[dict[str, Any]]
    local_storage: dict[str, str]
    page_state: PageState | None = None
    captured_at: AwareDatetime
    """
    ISO 8601 timestamp with timezone offset, e.g. 2026-05-02T09:15:00Z
    """


class Problem(BaseModel):
    """
    RFC 7807 problem details
    """

    type: AnyUrl
    """
    Stable URI identifying the problem class. Clients switch on this.
    """
    title: str
    status: conint(ge=100, le=599)
    detail: str | None = None
    instance: str | None = None


class Totals(BaseModel):
    session_minute: conint(ge=0) | None = None
    navigate: conint(ge=0) | None = None
    interact: conint(ge=0) | None = None
    wait: conint(ge=0) | None = None
    state_capture: conint(ge=0) | None = None
    screenshot_capture: conint(ge=0) | None = None


class Quotas(BaseModel):
    session_minute: conint(ge=0) | None = None
    navigate: conint(ge=0) | None = None
    interact: conint(ge=0) | None = None
    wait: conint(ge=0) | None = None
    state_capture: conint(ge=0) | None = None
    screenshot_capture: conint(ge=0) | None = None


class UsagePeriodSummary(BaseModel):
    period_start: AwareDatetime
    """
    ISO 8601 timestamp with timezone offset, e.g. 2026-05-02T09:15:00Z
    """
    period_end: AwareDatetime
    """
    ISO 8601 timestamp with timezone offset, e.g. 2026-05-02T09:15:00Z
    """
    tier: Literal[
        "free",
        "solo_manual",
        "team_manual",
        "agency_manual",
        "api_starter",
        "api_builder",
        "api_scale",
        "enterprise",
    ]
    totals: Totals
    quotas: Quotas


class PaginationQuery(BaseModel):
    limit: conint(ge=1, le=100) | None = 50
    cursor: constr(min_length=1, max_length=512) | None = None


class CreateSessionRequest(BaseModel):
    archetype: constr(pattern=r"^[a-z0-9_]+$", min_length=3, max_length=60) | None = (
        None
    )
    purpose: (
        Literal["production_customer", "cumulative_rig_validation", "test_domain_probe"]
        | None
    ) = None
    label: constr(max_length=120) | None = None
    metadata: dict[str, Any] | None = None
    profile_id: str | None = None
    behavioral_profile: Literal["casual", "regular", "power_user"] | None = None


class CreateSessionResponse(BaseModel):
    id: constr(
        pattern=r"^ses_[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$"
    )
    account_id: constr(
        pattern=r"^acc_[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$"
    )
    api_key_id: constr(
        pattern=r"^key_[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$"
    )
    status: Literal["creating", "ready", "busy", "destroyed", "errored"]
    archetype: constr(pattern=r"^[a-z0-9_]+$", min_length=3, max_length=60)
    purpose: Literal[
        "production_customer", "cumulative_rig_validation", "test_domain_probe"
    ]
    label: str | None
    metadata: dict[str, Any] | None
    egress_capabilities: EgressCapabilities | None
    egress_capability_report: dict[str, Any] | None
    created_at: AwareDatetime
    """
    ISO 8601 timestamp with timezone offset, e.g. 2026-05-02T09:15:00Z
    """
    updated_at: AwareDatetime
    """
    ISO 8601 timestamp with timezone offset, e.g. 2026-05-02T09:15:00Z
    """
    last_state_at: AwareDatetime | None
    """
    ISO 8601 timestamp with timezone offset, e.g. 2026-05-02T09:15:00Z
    """
    destroyed_at: AwareDatetime | None
    """
    ISO 8601 timestamp with timezone offset, e.g. 2026-05-02T09:15:00Z
    """


class NavigateRequest(BaseModel):
    url: AnyUrl
    timeout_ms: conint(ge=1000, le=120000) | None = None
    wait_until: Literal["load", "domcontentloaded", "networkidle"] | None = "load"


class NavigateResponse(BaseModel):
    url: AnyUrl
    status: conint(ge=100, le=599)
    final_url: AnyUrl
    duration_ms: conint(ge=0)


class Action(BaseModel):
    kind: Literal["tap"]
    selector: constr(min_length=1)


class Action1(BaseModel):
    kind: Literal["type"]
    selector: constr(min_length=1)
    text: constr(max_length=10000)
    delay_ms: conint(ge=0, le=500) | None = None
    sensitive: bool | None = None


class Action2(BaseModel):
    kind: Literal["scroll"]
    selector: constr(min_length=1) | None = None
    delta_x: int | None = 0
    delta_y: int | None = 0


class Action3(BaseModel):
    kind: Literal["press"]
    key: constr(min_length=1, max_length=20)


class InteractRequest(BaseModel):
    action: Action | Action1 | Action2 | Action3
    timeout_ms: conint(ge=100, le=60000) | None = None


class InteractResponse(BaseModel):
    ok: Literal[True]
    duration_ms: conint(ge=0)


class Condition(BaseModel):
    kind: Literal["selector"]
    selector: constr(min_length=1)


class Condition1(BaseModel):
    kind: Literal["selector_hidden"]
    selector: constr(min_length=1)


class Condition2(BaseModel):
    kind: Literal["url_matches"]
    pattern: constr(min_length=1)


class Condition3(BaseModel):
    kind: Literal["time"]
    ms: conint(ge=0, le=60000)


class WaitRequest(BaseModel):
    condition: Condition | Condition1 | Condition2 | Condition3
    timeout_ms: conint(ge=100, le=120000) | None = None


class WaitResponse(BaseModel):
    satisfied: bool
    duration_ms: conint(ge=0)


class CaptureRequest(BaseModel):
    kind: Literal["screenshot", "dom_snapshot", "pdf"]
    full_page: bool | None = False


class CaptureResponse(BaseModel):
    kind: Literal["screenshot", "dom_snapshot", "pdf"]
    data: str
    encoding: Literal["base64", "utf8"]
    byte_size: conint(ge=0)
    duration_ms: conint(ge=0)


class Extract(BaseModel):
    type: Literal["text", "attribute"]
    attribute: str | None = None
    selector: str | None = None


class Extraction(BaseModel):
    name: constr(min_length=1)
    selector: constr(min_length=1)
    type: Literal["text", "attribute", "list"]
    attribute: str | None = None
    transform: Literal["number"] | None = None
    extract: dict[str, Extract] | None = None


class ExtractRequest(BaseModel):
    extractions: list[Extraction] = Field(..., max_length=100, min_length=1)


class ExtractResponse(BaseModel):
    value: dict[str, Any]


class SearchRequest(BaseModel):
    query: constr(min_length=1)
    search_selector: str | None = None
    submit: bool | None = True
    wait_for_results_selector: str | None = None
    timeout_seconds: conint(ge=1, le=120) | None = None


class SearchResponse(BaseModel):
    submitted: bool
    results_visible: bool | None = None


class SessionLoginRequest(BaseModel):
    username: constr(min_length=1)
    password: constr(min_length=1)
    username_selector: str | None = None
    password_selector: str | None = None
    submit_selector: str | None = None
    success_selector: str | None = None
    timeout_seconds: conint(ge=1, le=120) | None = None


class SessionLoginResponse(BaseModel):
    logged_in: bool
    post_login_url: str | None = None


class CreateApiKeyRequest(BaseModel):
    name: constr(min_length=1, max_length=120)
    scopes: list[
        Literal[
            "read",
            "write",
            "admin",
            "account_owner",
            "driftstack_internal_admin",
            "gui_control",
            "read:sessions",
            "write:sessions",
            "read:profiles",
            "write:profiles",
            "admin:profiles",
            "read:webhooks",
            "write:webhooks",
            "admin:webhooks",
            "read:api-keys",
            "admin:api-keys",
            "read:billing",
            "admin:billing",
            "read:audit",
        ]
    ] = Field(..., min_length=1)
    expires_at: AwareDatetime | None = None
    """
    ISO 8601 timestamp with timezone offset, e.g. 2026-05-02T09:15:00Z
    """


class CreateApiKeyResponse(BaseModel):
    id: constr(
        pattern=r"^key_[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$"
    )
    name: str
    key_prefix: str
    scopes: list[
        Literal[
            "read",
            "write",
            "admin",
            "account_owner",
            "driftstack_internal_admin",
            "gui_control",
            "read:sessions",
            "write:sessions",
            "read:profiles",
            "write:profiles",
            "admin:profiles",
            "read:webhooks",
            "write:webhooks",
            "admin:webhooks",
            "read:api-keys",
            "admin:api-keys",
            "read:billing",
            "admin:billing",
            "read:audit",
        ]
    ]
    last_used_at: AwareDatetime | None
    """
    ISO 8601 timestamp with timezone offset, e.g. 2026-05-02T09:15:00Z
    """
    revoked_at: AwareDatetime | None
    """
    ISO 8601 timestamp with timezone offset, e.g. 2026-05-02T09:15:00Z
    """
    expires_at: AwareDatetime | None
    """
    ISO 8601 timestamp with timezone offset, e.g. 2026-05-02T09:15:00Z
    """
    created_at: AwareDatetime
    """
    ISO 8601 timestamp with timezone offset, e.g. 2026-05-02T09:15:00Z
    """
    plaintext: str
    """
    The plaintext key. Shown once at creation; not retrievable later.
    """


class DeliveryCounts(BaseModel):
    delivered: conint(ge=0)
    failed: conint(ge=0)
    dlq: conint(ge=0)


class WebhookEndpoint(BaseModel):
    id: constr(
        pattern=r"^whk_[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$"
    )
    url: AnyUrl
    secret_prefix: str
    prev_secret_prefix: str | None
    rotation_grace_expires_at: AwareDatetime | None
    """
    ISO 8601 timestamp with timezone offset, e.g. 2026-05-02T09:15:00Z
    """
    events: list[
        Literal[
            "session.completed",
            "session.failed",
            "quota.warning_80pct",
            "quota.exceeded",
            "api_key.revoked",
            "session.egress_capability_changed",
            "test.ping",
            "crypto.order.paid",
            "crypto.order.failed",
            "session.challenge_detected",
            "session.profile_save_failed",
        ]
    ]
    description: str | None
    active: bool
    consecutive_failures: conint(ge=0)
    last_success_at: AwareDatetime | None
    """
    ISO 8601 timestamp with timezone offset, e.g. 2026-05-02T09:15:00Z
    """
    last_failure_at: AwareDatetime | None
    """
    ISO 8601 timestamp with timezone offset, e.g. 2026-05-02T09:15:00Z
    """
    disabled_at: AwareDatetime | None
    """
    ISO 8601 timestamp with timezone offset, e.g. 2026-05-02T09:15:00Z
    """
    delivery_counts: DeliveryCounts
    created_at: AwareDatetime
    """
    ISO 8601 timestamp with timezone offset, e.g. 2026-05-02T09:15:00Z
    """


class CreateWebhookRequest(BaseModel):
    url: AnyUrl
    events: list[
        Literal[
            "session.completed",
            "session.failed",
            "quota.warning_80pct",
            "quota.exceeded",
            "api_key.revoked",
            "session.egress_capability_changed",
            "crypto.order.paid",
            "crypto.order.failed",
            "session.challenge_detected",
            "session.profile_save_failed",
        ]
    ] = Field(..., max_length=10, min_length=1)
    description: constr(max_length=200) | None = None


class CreateWebhookResponse(BaseModel):
    id: constr(
        pattern=r"^whk_[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$"
    )
    url: AnyUrl
    secret_prefix: str
    prev_secret_prefix: str | None
    rotation_grace_expires_at: AwareDatetime | None
    """
    ISO 8601 timestamp with timezone offset, e.g. 2026-05-02T09:15:00Z
    """
    events: list[
        Literal[
            "session.completed",
            "session.failed",
            "quota.warning_80pct",
            "quota.exceeded",
            "api_key.revoked",
            "session.egress_capability_changed",
            "test.ping",
            "crypto.order.paid",
            "crypto.order.failed",
            "session.challenge_detected",
            "session.profile_save_failed",
        ]
    ]
    description: str | None
    active: bool
    consecutive_failures: conint(ge=0)
    last_success_at: AwareDatetime | None
    """
    ISO 8601 timestamp with timezone offset, e.g. 2026-05-02T09:15:00Z
    """
    last_failure_at: AwareDatetime | None
    """
    ISO 8601 timestamp with timezone offset, e.g. 2026-05-02T09:15:00Z
    """
    disabled_at: AwareDatetime | None
    """
    ISO 8601 timestamp with timezone offset, e.g. 2026-05-02T09:15:00Z
    """
    delivery_counts: DeliveryCounts
    created_at: AwareDatetime
    """
    ISO 8601 timestamp with timezone offset, e.g. 2026-05-02T09:15:00Z
    """
    secret: str
    """
    Plaintext signing secret. Returned ONCE; not retrievable later.
    """


class WebhookDelivery(BaseModel):
    id: constr(
        pattern=r"^wdl_[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$"
    )
    webhook_id: constr(
        pattern=r"^whk_[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$"
    )
    event_id: UUID
    event_type: Literal[
        "session.completed",
        "session.failed",
        "quota.warning_80pct",
        "quota.exceeded",
        "api_key.revoked",
        "session.egress_capability_changed",
        "test.ping",
        "crypto.order.paid",
        "crypto.order.failed",
        "session.challenge_detected",
        "session.profile_save_failed",
    ]
    status: Literal["pending", "in_flight", "delivered", "failed", "dlq"]
    attempts: conint(ge=0)
    next_attempt_at: AwareDatetime
    """
    ISO 8601 timestamp with timezone offset, e.g. 2026-05-02T09:15:00Z
    """
    last_response_status: int | None
    last_response_excerpt: str | None
    last_error: str | None
    delivered_at: AwareDatetime | None
    """
    ISO 8601 timestamp with timezone offset, e.g. 2026-05-02T09:15:00Z
    """
    created_at: AwareDatetime
    """
    ISO 8601 timestamp with timezone offset, e.g. 2026-05-02T09:15:00Z
    """


class ListDeliveriesQuery(BaseModel):
    limit: conint(ge=1, le=100) | None = 50
    cursor: constr(min_length=1, max_length=512) | None = None
    status: Literal["pending", "in_flight", "delivered", "failed", "dlq"] | None = None


class AdminAccount(BaseModel):
    id: constr(
        pattern=r"^acc_[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$"
    )
    email: EmailStr
    name: str | None
    tier: Literal[
        "free",
        "solo_manual",
        "team_manual",
        "agency_manual",
        "api_starter",
        "api_builder",
        "api_scale",
        "enterprise",
    ]
    status: Literal["active", "suspended", "deleted"]
    created_at: AwareDatetime
    """
    ISO 8601 timestamp with timezone offset, e.g. 2026-05-02T09:15:00Z
    """
    updated_at: AwareDatetime
    """
    ISO 8601 timestamp with timezone offset, e.g. 2026-05-02T09:15:00Z
    """


class AdminAuditLogEntry(BaseModel):
    id: UUID
    admin_account_id: str
    admin_key_id: str
    action: Literal[
        "account.tier_changed",
        "account.suspended",
        "account.unsuspended",
        "webhook_delivery.replayed",
        "webhook_delivery.requeued",
        "webhook_delivery.discarded",
        "rate_limit_override.set",
        "rate_limit_override.cleared",
        "session.destroyed_by_admin",
        "api_key.revoked_by_admin",
        "audit_note.added",
        "refund.recorded",
        "incident.created",
        "incident.updated",
        "incident.resolved",
        "incident.reopened",
        "status_subscriber.force_unsubscribed",
        "status_subscriber.purged",
        "status_subscriber.force_subscribed",
        "mac_node.livekit_registered",
        "mac_node.control",
        "pricing.updated",
        "secret.created",
        "secret.updated",
        "secret.deleted",
        "secret.revealed",
        "crypto_order.swept",
        "crypto_order.ipn_applied",
        "crypto_order.note_updated",
        "validation_schedule.upserted",
        "validation_schedule.removed",
        "validation_schedule.triggered",
        "account.deleted",
    ]
    target_account_id: str | None
    target_resource_id: str | None
    input_payload: dict[str, Any] | None
    result: str
    ip_address: str | None
    timestamp: AwareDatetime
    """
    ISO 8601 timestamp with timezone offset, e.g. 2026-05-02T09:15:00Z
    """


class Subscription(BaseModel):
    tier: Literal[
        "free",
        "solo_manual",
        "team_manual",
        "agency_manual",
        "api_starter",
        "api_builder",
        "api_scale",
        "enterprise",
    ]
    status: Literal[
        "incomplete",
        "incomplete_expired",
        "trialing",
        "active",
        "past_due",
        "canceled",
        "unpaid",
        "paused",
    ]
    stripe_subscription_id: str
    current_period_end: AwareDatetime | None
    """
    ISO 8601 timestamp with timezone offset, e.g. 2026-05-02T09:15:00Z
    """
    cancel_at_period_end: bool
    canceled_at: AwareDatetime | None
    """
    ISO 8601 timestamp with timezone offset, e.g. 2026-05-02T09:15:00Z
    """
    created_at: AwareDatetime
    """
    ISO 8601 timestamp with timezone offset, e.g. 2026-05-02T09:15:00Z
    """
    updated_at: AwareDatetime
    """
    ISO 8601 timestamp with timezone offset, e.g. 2026-05-02T09:15:00Z
    """


class GetBillingStateResponse(BaseModel):
    subscription: Subscription | None


class RotateApiKeyResponse(BaseModel):
    id: constr(
        pattern=r"^key_[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$"
    )
    name: str
    key_prefix: str
    scopes: list[
        Literal[
            "read",
            "write",
            "admin",
            "account_owner",
            "driftstack_internal_admin",
            "gui_control",
            "read:sessions",
            "write:sessions",
            "read:profiles",
            "write:profiles",
            "admin:profiles",
            "read:webhooks",
            "write:webhooks",
            "admin:webhooks",
            "read:api-keys",
            "admin:api-keys",
            "read:billing",
            "admin:billing",
            "read:audit",
        ]
    ]
    last_used_at: AwareDatetime | None
    """
    ISO 8601 timestamp with timezone offset, e.g. 2026-05-02T09:15:00Z
    """
    revoked_at: AwareDatetime | None
    """
    ISO 8601 timestamp with timezone offset, e.g. 2026-05-02T09:15:00Z
    """
    expires_at: AwareDatetime | None
    """
    ISO 8601 timestamp with timezone offset, e.g. 2026-05-02T09:15:00Z
    """
    created_at: AwareDatetime
    """
    ISO 8601 timestamp with timezone offset, e.g. 2026-05-02T09:15:00Z
    """
    plaintext: str
    """
    The plaintext key. Shown once at creation; not retrievable later.
    """
    rotated_from: str
    grace_period_ends_at: str


class RotateApiKeyRequest(BaseModel):
    name: str | None = None


class TeamInviteRequest(BaseModel):
    email: EmailStr
    role: Literal["member", "admin"] | None = None


class TeamInvite(BaseModel):
    id: str
    """
    Prefixed invite id (inv_<uuid>)
    """
    owner_account_id: str
    invitee_email: str
    role: Literal["member", "admin"]
    expires_at: str
    invited_by_account_id: str | None
    accepted_at: str | None
    created_at: str


class TeamMember(BaseModel):
    id: str
    """
    Prefixed membership id (mem_<uuid>)
    """
    owner_account_id: str
    member_account_id: str
    member_email: str
    role: Literal["member", "admin"]
    invited_at: str
    accepted_at: str
    invited_by_account_id: str | None


class TeamAcceptRequest(BaseModel):
    token: constr(min_length=20)


class TeamOwner(BaseModel):
    owner_account_id: str
    owner_email: str
    owner_name: str | None
    role: Literal["member", "admin"]
    membership_id: str


class UploadAvatarResponse(BaseModel):
    avatar_url: str | None
    content_type: Literal["image/png", "image/jpeg", "image/webp"]
    bytes: conint(ge=0)


class ByokAnthropicMetadata(BaseModel):
    has_key: bool
    set_at: str | None
    last_used_at: str | None


class PutByokAnthropicResponse(BaseModel):
    set_at: str


class PutByokAnthropicRequest(BaseModel):
    api_key: constr(min_length=1)
    """
    Plaintext Anthropic API key. Never echoed back.
    """


class BundledLlmSettings(BaseModel):
    consent: bool
    monthly_cap_usd_cents: conint(ge=0, le=1000000)


class PatchBundledLlmRequest(BaseModel):
    """
    At least one of consent / monthly_cap_usd_cents must be present.
    """

    consent: bool | None = None
    monthly_cap_usd_cents: conint(ge=0, le=1000000) | None = None


class Folder(BaseModel):
    name: str
    icon: str | None = None


class AccountOrganization(BaseModel):
    folders: list[Folder]
    tags: list[str]


class AccountProxyMetadata(BaseModel):
    id: str
    label: str
    scheme: Literal["socks5", "http", "openvpn", "wireguard"]
    host: str
    port: int
    username: str | None
    has_password: bool
    has_secret: bool
    created_at: str
    updated_at: str


class AccountProxyList(BaseModel):
    data: list[AccountProxyMetadata]


class Openvpn(BaseModel):
    config_blob: str
    username: str | None = None
    password: str | None = None


class Wireguard(BaseModel):
    private_key: str
    peer_public_key: str
    endpoint: str
    allowed_ips: str | None = None
    address: str | None = None
    dns: str | None = None


class AccountProxyInput(BaseModel):
    label: str
    scheme: Literal["socks5", "http", "openvpn", "wireguard"] | None = None
    host: str
    port: int
    username: str | None = None
    password: str | None = None
    openvpn: Openvpn | None = None
    wireguard: Wireguard | None = None


class AccountProxyTestResult1(BaseModel):
    ok: Literal[True]
    latency_ms: int


class AccountProxyTestResult2(BaseModel):
    ok: Literal[False]
    reason: str


class AccountProxyTestResult(
    RootModel[AccountProxyTestResult1 | AccountProxyTestResult2]
):
    root: AccountProxyTestResult1 | AccountProxyTestResult2


class BundledLlmStatus(BaseModel):
    consent: bool
    cap_cents: conint(ge=0)
    used_this_month_cents: conint(ge=0)
    remaining_cents: conint(ge=0)
    refused_count_this_month: conint(ge=0)
    month_started_at: str


class AccountAuditEntry(BaseModel):
    id: UUID
    account_id: str
    actor_type: Literal["customer", "system", "staff"]
    actor_account_id: str | None
    actor_key_id: str | None
    action: str
    target_resource_id: str | None
    payload: dict[str, Any] | None
    ip_address: str | None
    user_agent: str | None
    timestamp: str


class ListAccountAuditResponse(BaseModel):
    data: list[AccountAuditEntry]
    next_cursor: str | None


class ExportAccountAuditResponse(BaseModel):
    generated_at: str
    account_id: str
    row_count: conint(ge=0)
    truncated: bool
    data: list[AccountAuditEntry]


class CostThresholdState(
    RootModel[Literal["under-soft", "between-soft-and-hard", "over-hard"]]
):
    root: Literal["under-soft", "between-soft-and-hard", "over-hard"]


class CostBreakdown(BaseModel):
    computeCents: conint(ge=0)
    storageCents: conint(ge=0)
    egressCents: conint(ge=0)
    emailCents: conint(ge=0)
    llmCents: conint(ge=0)
    totalCents: conint(ge=0)
    thresholdState: CostThresholdState


class AccountCostResponse(BaseModel):
    account_id: str
    billing_cycle: constr(pattern=r"^\d{4}-\d{2}$")
    tier: Literal[
        "free",
        "solo_manual",
        "team_manual",
        "agency_manual",
        "api_starter",
        "api_builder",
        "api_scale",
        "enterprise",
    ]
    breakdown: CostBreakdown


class AccountNotificationsStream(RootModel[str]):
    root: str
    """
    Server-sent event stream of NotificationEvent frames for the calling account.
    """


class AgentSessionTranscriptStream(RootModel[str]):
    root: str
    """
    Server-sent event stream of transcript.entry frames; each frame carries an `id:` (the entry index) and a JSON `data:` payload of { index, entry }.
    """


class LiveKitInfo(BaseModel):
    ws_url: AnyUrl
    room: str
    token: str
    participant_identity: str
    expires_at: str


class RegisterMacNodeResponse(BaseModel):
    mac_node_id: str
    livekit_registered_at: str
    ws_url: str


class Livekit1(BaseModel):
    api_key: constr(min_length=1, max_length=256)
    api_secret: constr(min_length=1, max_length=1024)
    ws_url: AnyUrl


class RegisterMacNodeRequest(BaseModel):
    mac_node_id: UUID
    livekit: Livekit1


class AdminSubscriptionStatsResponse(BaseModel):
    by_tier: dict[str, conint(ge=0)]
    total_active: conint(ge=0)


class Features(BaseModel):
    billing: bool
    livekit: bool
    crypto: bool
    oauth_client: bool
    sentry: bool
    permissive_cors: bool


class OwnerPlatformStatusResponse(BaseModel):
    features: Features


class Tier(BaseModel):
    tier: str
    monthly_cents: conint(ge=0)


class OwnerPricingResponse(BaseModel):
    tiers: list[Tier]


class OwnerPricingEditResponse(BaseModel):
    tier: str
    monthly_cents: conint(ge=0)


class OwnerPricingEditRequest(BaseModel):
    monthly_cents: conint(le=1000000, gt=0)


class LaunchProfileRequest(BaseModel):
    label: str | None = None
