# generated by datamodel-codegen:
#   filename:  openapi.json
#   timestamp: 2026-05-02T15:47:41+00:00

from __future__ import annotations

from typing import Any, Literal
from uuid import UUID

from pydantic import AnyUrl, AwareDatetime, BaseModel, EmailStr, conint, constr


class Account(BaseModel):
    id: constr(
        pattern=r"^acc_[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$"
    )
    email: EmailStr
    name: str | None
    tier: Literal["free", "starter", "solo", "builder", "scale", "enterprise"]
    status: Literal["active", "suspended", "deleted"]
    created_at: AwareDatetime
    """
    ISO 8601 timestamp with timezone offset, e.g. 2026-05-02T09:15:00Z
    """
    updated_at: AwareDatetime
    """
    ISO 8601 timestamp with timezone offset, e.g. 2026-05-02T09:15:00Z
    """


class ApiKey(BaseModel):
    id: constr(
        pattern=r"^key_[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$"
    )
    name: str
    key_prefix: str
    scopes: list[Literal["read", "write", "admin"]]
    last_used_at: AwareDatetime | None
    """
    ISO 8601 timestamp with timezone offset, e.g. 2026-05-02T09:15:00Z
    """
    revoked_at: AwareDatetime | None
    """
    ISO 8601 timestamp with timezone offset, e.g. 2026-05-02T09:15:00Z
    """
    expires_at: AwareDatetime | None
    """
    ISO 8601 timestamp with timezone offset, e.g. 2026-05-02T09:15:00Z
    """
    created_at: AwareDatetime
    """
    ISO 8601 timestamp with timezone offset, e.g. 2026-05-02T09:15:00Z
    """


class Session(BaseModel):
    id: constr(
        pattern=r"^ses_[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$"
    )
    account_id: constr(
        pattern=r"^acc_[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$"
    )
    api_key_id: constr(
        pattern=r"^key_[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$"
    )
    status: Literal["creating", "ready", "busy", "destroyed", "errored"]
    archetype: constr(pattern=r"^[a-z0-9_]+$", min_length=3, max_length=60)
    label: str | None
    metadata: dict[str, Any] | None
    created_at: AwareDatetime
    """
    ISO 8601 timestamp with timezone offset, e.g. 2026-05-02T09:15:00Z
    """
    updated_at: AwareDatetime
    """
    ISO 8601 timestamp with timezone offset, e.g. 2026-05-02T09:15:00Z
    """
    last_state_at: AwareDatetime | None
    """
    ISO 8601 timestamp with timezone offset, e.g. 2026-05-02T09:15:00Z
    """
    destroyed_at: AwareDatetime | None
    """
    ISO 8601 timestamp with timezone offset, e.g. 2026-05-02T09:15:00Z
    """


class Problem(BaseModel):
    """
    RFC 7807 problem details
    """

    type: AnyUrl
    """
    Stable URI identifying the problem class. Clients switch on this.
    """
    title: str
    status: conint(ge=100, le=599)
    detail: str | None = None
    instance: str | None = None


class Totals(BaseModel):
    session_minute: conint(ge=0) | None = None
    navigate: conint(ge=0) | None = None
    interact: conint(ge=0) | None = None
    wait: conint(ge=0) | None = None
    state_capture: conint(ge=0) | None = None
    screenshot_capture: conint(ge=0) | None = None


class Quotas(BaseModel):
    session_minute: conint(ge=0) | None = None
    navigate: conint(ge=0) | None = None
    interact: conint(ge=0) | None = None
    wait: conint(ge=0) | None = None
    state_capture: conint(ge=0) | None = None
    screenshot_capture: conint(ge=0) | None = None


class UsagePeriodSummary(BaseModel):
    period_start: AwareDatetime
    """
    ISO 8601 timestamp with timezone offset, e.g. 2026-05-02T09:15:00Z
    """
    period_end: AwareDatetime
    """
    ISO 8601 timestamp with timezone offset, e.g. 2026-05-02T09:15:00Z
    """
    tier: Literal["free", "starter", "solo", "builder", "scale", "enterprise"]
    totals: Totals
    quotas: Quotas


class AdminAccount(BaseModel):
    id: constr(
        pattern=r"^acc_[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$"
    )
    email: EmailStr
    name: str | None
    tier: Literal["free", "starter", "solo", "builder", "scale", "enterprise"]
    status: Literal["active", "suspended", "deleted"]
    created_at: AwareDatetime
    """
    ISO 8601 timestamp with timezone offset, e.g. 2026-05-02T09:15:00Z
    """
    updated_at: AwareDatetime
    """
    ISO 8601 timestamp with timezone offset, e.g. 2026-05-02T09:15:00Z
    """


class AdminAuditLogEntry(BaseModel):
    id: UUID
    admin_account_id: str
    admin_key_id: str
    action: Literal[
        "account.tier_changed",
        "account.suspended",
        "account.unsuspended",
        "webhook_delivery.replayed",
        "webhook_delivery.requeued",
        "rate_limit_override.set",
        "rate_limit_override.cleared",
    ]
    target_account_id: str | None
    target_resource_id: str | None
    input_payload: dict[str, Any] | None
    result: str
    ip_address: str | None
    timestamp: AwareDatetime
    """
    ISO 8601 timestamp with timezone offset, e.g. 2026-05-02T09:15:00Z
    """


class WebhookDelivery(BaseModel):
    id: constr(
        pattern=r"^wdl_[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$"
    )
    webhook_id: constr(
        pattern=r"^whk_[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$"
    )
    event_id: UUID
    event_type: Literal[
        "session.completed",
        "session.failed",
        "quota.warning_80pct",
        "quota.exceeded",
        "api_key.revoked",
    ]
    status: Literal["pending", "in_flight", "delivered", "failed", "dlq"]
    attempts: conint(ge=0)
    next_attempt_at: AwareDatetime
    """
    ISO 8601 timestamp with timezone offset, e.g. 2026-05-02T09:15:00Z
    """
    last_response_status: int | None
    last_response_excerpt: str | None
    last_error: str | None
    delivered_at: AwareDatetime | None
    """
    ISO 8601 timestamp with timezone offset, e.g. 2026-05-02T09:15:00Z
    """
    created_at: AwareDatetime
    """
    ISO 8601 timestamp with timezone offset, e.g. 2026-05-02T09:15:00Z
    """
