# generated by datamodel-codegen:
#   filename:  openapi.json
#   timestamp: 2026-05-09T09:47:52+00:00

from __future__ import annotations

from typing import Any, Literal
from uuid import UUID

from pydantic import AnyUrl, AwareDatetime, BaseModel, EmailStr, Field, conint, constr


class Account(BaseModel):
    id: constr(
        pattern=r"^acc_[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$"
    )
    email: EmailStr
    name: str | None
    tier: Literal[
        "trial_pack",
        "solo_manual",
        "team_manual",
        "agency_manual",
        "api_starter",
        "api_builder",
        "api_scale",
        "enterprise",
    ]
    status: Literal["active", "suspended", "deleted"]
    created_at: AwareDatetime
    """
    ISO 8601 timestamp with timezone offset, e.g. 2026-05-02T09:15:00Z
    """
    updated_at: AwareDatetime
    """
    ISO 8601 timestamp with timezone offset, e.g. 2026-05-02T09:15:00Z
    """


class Team(BaseModel):
    owner_account_id: str
    role: Literal["admin", "member"]
    membership_id: str


class AccountMeResponse(BaseModel):
    id: str
    email: EmailStr
    name: str | None
    tier: Literal[
        "trial_pack",
        "solo_manual",
        "team_manual",
        "agency_manual",
        "api_starter",
        "api_builder",
        "api_scale",
        "enterprise",
    ]
    status: Literal["active", "suspended", "deleted"]
    timezone: str | None
    slug: str | None
    region: Literal["us", "eu", "apac"] | None
    avatar_url: str | None
    mfa_enrolled: bool
    concurrent_session_cap: conint(ge=0)
    concurrent_session_active: conint(ge=0)
    profile_cap: conint(ge=0) | None
    profile_count: conint(ge=0)
    teams: list[Team]


class UpdateAccountMeRequest(BaseModel):
    name: constr(min_length=1, max_length=120) | None = None
    timezone: (
        constr(
            pattern=r"^[A-Za-z]+(?:\/[A-Za-z0-9_+-]+)+$", min_length=1, max_length=64
        )
        | None
    ) = None
    slug: (
        constr(
            pattern=r"^[a-z0-9](?:[a-z0-9-]*[a-z0-9])?$", min_length=3, max_length=32
        )
        | None
    ) = None
    region: Literal["us", "eu", "apac"] | None = None


class ApiKey(BaseModel):
    id: constr(
        pattern=r"^key_[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$"
    )
    name: str
    key_prefix: str
    scopes: list[
        Literal[
            "read",
            "write",
            "admin",
            "account_owner",
            "driftstack_internal_admin",
            "gui_control",
        ]
    ]
    last_used_at: AwareDatetime | None
    """
    ISO 8601 timestamp with timezone offset, e.g. 2026-05-02T09:15:00Z
    """
    revoked_at: AwareDatetime | None
    """
    ISO 8601 timestamp with timezone offset, e.g. 2026-05-02T09:15:00Z
    """
    expires_at: AwareDatetime | None
    """
    ISO 8601 timestamp with timezone offset, e.g. 2026-05-02T09:15:00Z
    """
    created_at: AwareDatetime
    """
    ISO 8601 timestamp with timezone offset, e.g. 2026-05-02T09:15:00Z
    """


class Session(BaseModel):
    id: constr(
        pattern=r"^ses_[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$"
    )
    account_id: constr(
        pattern=r"^acc_[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$"
    )
    api_key_id: constr(
        pattern=r"^key_[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$"
    )
    status: Literal["creating", "ready", "busy", "destroyed", "errored"]
    archetype: constr(pattern=r"^[a-z0-9_]+$", min_length=3, max_length=60)
    purpose: Literal[
        "production_customer", "cumulative_rig_validation", "test_domain_probe"
    ]
    label: str | None
    metadata: dict[str, Any] | None
    created_at: AwareDatetime
    """
    ISO 8601 timestamp with timezone offset, e.g. 2026-05-02T09:15:00Z
    """
    updated_at: AwareDatetime
    """
    ISO 8601 timestamp with timezone offset, e.g. 2026-05-02T09:15:00Z
    """
    last_state_at: AwareDatetime | None
    """
    ISO 8601 timestamp with timezone offset, e.g. 2026-05-02T09:15:00Z
    """
    destroyed_at: AwareDatetime | None
    """
    ISO 8601 timestamp with timezone offset, e.g. 2026-05-02T09:15:00Z
    """


class SessionState(BaseModel):
    url: AnyUrl | None
    title: str | None
    cookies: list[dict[str, Any]]
    local_storage: dict[str, str]
    captured_at: AwareDatetime
    """
    ISO 8601 timestamp with timezone offset, e.g. 2026-05-02T09:15:00Z
    """


class Problem(BaseModel):
    """
    RFC 7807 problem details
    """

    type: AnyUrl
    """
    Stable URI identifying the problem class. Clients switch on this.
    """
    title: str
    status: conint(ge=100, le=599)
    detail: str | None = None
    instance: str | None = None


class Totals(BaseModel):
    session_minute: conint(ge=0) | None = None
    navigate: conint(ge=0) | None = None
    interact: conint(ge=0) | None = None
    wait: conint(ge=0) | None = None
    state_capture: conint(ge=0) | None = None
    screenshot_capture: conint(ge=0) | None = None


class Quotas(BaseModel):
    session_minute: conint(ge=0) | None = None
    navigate: conint(ge=0) | None = None
    interact: conint(ge=0) | None = None
    wait: conint(ge=0) | None = None
    state_capture: conint(ge=0) | None = None
    screenshot_capture: conint(ge=0) | None = None


class UsagePeriodSummary(BaseModel):
    period_start: AwareDatetime
    """
    ISO 8601 timestamp with timezone offset, e.g. 2026-05-02T09:15:00Z
    """
    period_end: AwareDatetime
    """
    ISO 8601 timestamp with timezone offset, e.g. 2026-05-02T09:15:00Z
    """
    tier: Literal[
        "trial_pack",
        "solo_manual",
        "team_manual",
        "agency_manual",
        "api_starter",
        "api_builder",
        "api_scale",
        "enterprise",
    ]
    totals: Totals
    quotas: Quotas


class PaginationQuery(BaseModel):
    limit: conint(ge=1, le=100) | None = 50
    cursor: str | None = None


class CreateSessionRequest(BaseModel):
    archetype: constr(pattern=r"^[a-z0-9_]+$", min_length=3, max_length=60) | None = (
        None
    )
    purpose: (
        Literal["production_customer", "cumulative_rig_validation", "test_domain_probe"]
        | None
    ) = None
    label: constr(max_length=120) | None = None
    metadata: dict[str, Any] | None = None


class CreateSessionResponse(BaseModel):
    id: constr(
        pattern=r"^ses_[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$"
    )
    account_id: constr(
        pattern=r"^acc_[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$"
    )
    api_key_id: constr(
        pattern=r"^key_[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$"
    )
    status: Literal["creating", "ready", "busy", "destroyed", "errored"]
    archetype: constr(pattern=r"^[a-z0-9_]+$", min_length=3, max_length=60)
    purpose: Literal[
        "production_customer", "cumulative_rig_validation", "test_domain_probe"
    ]
    label: str | None
    metadata: dict[str, Any] | None
    created_at: AwareDatetime
    """
    ISO 8601 timestamp with timezone offset, e.g. 2026-05-02T09:15:00Z
    """
    updated_at: AwareDatetime
    """
    ISO 8601 timestamp with timezone offset, e.g. 2026-05-02T09:15:00Z
    """
    last_state_at: AwareDatetime | None
    """
    ISO 8601 timestamp with timezone offset, e.g. 2026-05-02T09:15:00Z
    """
    destroyed_at: AwareDatetime | None
    """
    ISO 8601 timestamp with timezone offset, e.g. 2026-05-02T09:15:00Z
    """


class NavigateRequest(BaseModel):
    url: AnyUrl
    timeout_ms: conint(ge=1000, le=120000) | None = None
    wait_until: Literal["load", "domcontentloaded", "networkidle"] | None = "load"


class NavigateResponse(BaseModel):
    url: AnyUrl
    status: conint(ge=100, le=599)
    final_url: AnyUrl
    duration_ms: conint(ge=0)


class Action(BaseModel):
    kind: Literal["tap"]
    selector: constr(min_length=1)


class Action1(BaseModel):
    kind: Literal["type"]
    selector: constr(min_length=1)
    text: constr(max_length=10000)
    delay_ms: conint(ge=0, le=500) | None = None


class Action2(BaseModel):
    kind: Literal["scroll"]
    selector: constr(min_length=1) | None = None
    delta_x: int | None = 0
    delta_y: int | None = 0


class Action3(BaseModel):
    kind: Literal["press"]
    key: constr(min_length=1, max_length=20)


class InteractRequest(BaseModel):
    action: Action | Action1 | Action2 | Action3
    timeout_ms: conint(ge=100, le=60000) | None = None


class InteractResponse(BaseModel):
    ok: Literal[True]
    duration_ms: conint(ge=0)


class Condition(BaseModel):
    kind: Literal["selector"]
    selector: constr(min_length=1)


class Condition1(BaseModel):
    kind: Literal["selector_hidden"]
    selector: constr(min_length=1)


class Condition2(BaseModel):
    kind: Literal["url_matches"]
    pattern: constr(min_length=1)


class Condition3(BaseModel):
    kind: Literal["time"]
    ms: conint(ge=0, le=60000)


class WaitRequest(BaseModel):
    condition: Condition | Condition1 | Condition2 | Condition3
    timeout_ms: conint(ge=100, le=120000) | None = None


class WaitResponse(BaseModel):
    satisfied: bool
    duration_ms: conint(ge=0)


class CaptureRequest(BaseModel):
    kind: Literal["screenshot", "dom_snapshot", "pdf"]
    full_page: bool | None = False


class CaptureResponse(BaseModel):
    kind: Literal["screenshot", "dom_snapshot", "pdf"]
    data: str
    encoding: Literal["base64", "utf8"]
    byte_size: conint(ge=0)
    duration_ms: conint(ge=0)


class CreateApiKeyRequest(BaseModel):
    name: constr(min_length=1, max_length=120)
    scopes: list[
        Literal[
            "read",
            "write",
            "admin",
            "account_owner",
            "driftstack_internal_admin",
            "gui_control",
        ]
    ] = Field(..., min_length=1)
    expires_at: AwareDatetime | None = None
    """
    ISO 8601 timestamp with timezone offset, e.g. 2026-05-02T09:15:00Z
    """


class CreateApiKeyResponse(BaseModel):
    id: constr(
        pattern=r"^key_[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$"
    )
    name: str
    key_prefix: str
    scopes: list[
        Literal[
            "read",
            "write",
            "admin",
            "account_owner",
            "driftstack_internal_admin",
            "gui_control",
        ]
    ]
    last_used_at: AwareDatetime | None
    """
    ISO 8601 timestamp with timezone offset, e.g. 2026-05-02T09:15:00Z
    """
    revoked_at: AwareDatetime | None
    """
    ISO 8601 timestamp with timezone offset, e.g. 2026-05-02T09:15:00Z
    """
    expires_at: AwareDatetime | None
    """
    ISO 8601 timestamp with timezone offset, e.g. 2026-05-02T09:15:00Z
    """
    created_at: AwareDatetime
    """
    ISO 8601 timestamp with timezone offset, e.g. 2026-05-02T09:15:00Z
    """
    plaintext: str
    """
    The plaintext key. Shown once at creation; not retrievable later.
    """


class DeliveryCounts(BaseModel):
    delivered: conint(ge=0)
    failed: conint(ge=0)
    dlq: conint(ge=0)


class WebhookEndpoint(BaseModel):
    id: constr(
        pattern=r"^whk_[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$"
    )
    url: AnyUrl
    secret_prefix: str
    prev_secret_prefix: str | None
    rotation_grace_expires_at: AwareDatetime | None
    """
    ISO 8601 timestamp with timezone offset, e.g. 2026-05-02T09:15:00Z
    """
    events: list[
        Literal[
            "session.completed",
            "session.failed",
            "quota.warning_80pct",
            "quota.exceeded",
            "api_key.revoked",
            "test.ping",
        ]
    ]
    description: str | None
    active: bool
    consecutive_failures: conint(ge=0)
    last_success_at: AwareDatetime | None
    """
    ISO 8601 timestamp with timezone offset, e.g. 2026-05-02T09:15:00Z
    """
    last_failure_at: AwareDatetime | None
    """
    ISO 8601 timestamp with timezone offset, e.g. 2026-05-02T09:15:00Z
    """
    disabled_at: AwareDatetime | None
    """
    ISO 8601 timestamp with timezone offset, e.g. 2026-05-02T09:15:00Z
    """
    delivery_counts: DeliveryCounts
    created_at: AwareDatetime
    """
    ISO 8601 timestamp with timezone offset, e.g. 2026-05-02T09:15:00Z
    """


class CreateWebhookRequest(BaseModel):
    url: AnyUrl
    events: list[
        Literal[
            "session.completed",
            "session.failed",
            "quota.warning_80pct",
            "quota.exceeded",
            "api_key.revoked",
        ]
    ] = Field(..., max_length=10, min_length=1)
    description: constr(max_length=200) | None = None


class CreateWebhookResponse(BaseModel):
    id: constr(
        pattern=r"^whk_[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$"
    )
    url: AnyUrl
    secret_prefix: str
    prev_secret_prefix: str | None
    rotation_grace_expires_at: AwareDatetime | None
    """
    ISO 8601 timestamp with timezone offset, e.g. 2026-05-02T09:15:00Z
    """
    events: list[
        Literal[
            "session.completed",
            "session.failed",
            "quota.warning_80pct",
            "quota.exceeded",
            "api_key.revoked",
            "test.ping",
        ]
    ]
    description: str | None
    active: bool
    consecutive_failures: conint(ge=0)
    last_success_at: AwareDatetime | None
    """
    ISO 8601 timestamp with timezone offset, e.g. 2026-05-02T09:15:00Z
    """
    last_failure_at: AwareDatetime | None
    """
    ISO 8601 timestamp with timezone offset, e.g. 2026-05-02T09:15:00Z
    """
    disabled_at: AwareDatetime | None
    """
    ISO 8601 timestamp with timezone offset, e.g. 2026-05-02T09:15:00Z
    """
    delivery_counts: DeliveryCounts
    created_at: AwareDatetime
    """
    ISO 8601 timestamp with timezone offset, e.g. 2026-05-02T09:15:00Z
    """
    secret: str
    """
    Plaintext signing secret. Returned ONCE; not retrievable later.
    """


class WebhookDelivery(BaseModel):
    id: constr(
        pattern=r"^wdl_[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$"
    )
    webhook_id: constr(
        pattern=r"^whk_[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$"
    )
    event_id: UUID
    event_type: Literal[
        "session.completed",
        "session.failed",
        "quota.warning_80pct",
        "quota.exceeded",
        "api_key.revoked",
        "test.ping",
    ]
    status: Literal["pending", "in_flight", "delivered", "failed", "dlq"]
    attempts: conint(ge=0)
    next_attempt_at: AwareDatetime
    """
    ISO 8601 timestamp with timezone offset, e.g. 2026-05-02T09:15:00Z
    """
    last_response_status: int | None
    last_response_excerpt: str | None
    last_error: str | None
    delivered_at: AwareDatetime | None
    """
    ISO 8601 timestamp with timezone offset, e.g. 2026-05-02T09:15:00Z
    """
    created_at: AwareDatetime
    """
    ISO 8601 timestamp with timezone offset, e.g. 2026-05-02T09:15:00Z
    """


class ListDeliveriesQuery(BaseModel):
    limit: conint(ge=1, le=100) | None = 50
    cursor: str | None = None
    status: Literal["pending", "in_flight", "delivered", "failed", "dlq"] | None = None


class AdminAccount(BaseModel):
    id: constr(
        pattern=r"^acc_[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$"
    )
    email: EmailStr
    name: str | None
    tier: Literal[
        "trial_pack",
        "solo_manual",
        "team_manual",
        "agency_manual",
        "api_starter",
        "api_builder",
        "api_scale",
        "enterprise",
    ]
    status: Literal["active", "suspended", "deleted"]
    created_at: AwareDatetime
    """
    ISO 8601 timestamp with timezone offset, e.g. 2026-05-02T09:15:00Z
    """
    updated_at: AwareDatetime
    """
    ISO 8601 timestamp with timezone offset, e.g. 2026-05-02T09:15:00Z
    """


class AdminAuditLogEntry(BaseModel):
    id: UUID
    admin_account_id: str
    admin_key_id: str
    action: Literal[
        "account.tier_changed",
        "account.suspended",
        "account.unsuspended",
        "webhook_delivery.replayed",
        "webhook_delivery.requeued",
        "rate_limit_override.set",
        "rate_limit_override.cleared",
        "session.destroyed_by_admin",
        "api_key.revoked_by_admin",
        "audit_note.added",
        "refund.recorded",
        "incident.created",
        "incident.updated",
        "incident.resolved",
        "status_subscriber.force_unsubscribed",
        "status_subscriber.purged",
    ]
    target_account_id: str | None
    target_resource_id: str | None
    input_payload: dict[str, Any] | None
    result: str
    ip_address: str | None
    timestamp: AwareDatetime
    """
    ISO 8601 timestamp with timezone offset, e.g. 2026-05-02T09:15:00Z
    """


class RotateApiKeyResponse(BaseModel):
    id: constr(
        pattern=r"^key_[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$"
    )
    name: str
    key_prefix: str
    scopes: list[
        Literal[
            "read",
            "write",
            "admin",
            "account_owner",
            "driftstack_internal_admin",
            "gui_control",
        ]
    ]
    last_used_at: AwareDatetime | None
    """
    ISO 8601 timestamp with timezone offset, e.g. 2026-05-02T09:15:00Z
    """
    revoked_at: AwareDatetime | None
    """
    ISO 8601 timestamp with timezone offset, e.g. 2026-05-02T09:15:00Z
    """
    expires_at: AwareDatetime | None
    """
    ISO 8601 timestamp with timezone offset, e.g. 2026-05-02T09:15:00Z
    """
    created_at: AwareDatetime
    """
    ISO 8601 timestamp with timezone offset, e.g. 2026-05-02T09:15:00Z
    """
    plaintext: str
    """
    The plaintext key. Shown once at creation; not retrievable later.
    """
    rotated_from: str
    grace_period_ends_at: str


class RotateApiKeyRequest(BaseModel):
    name: str | None = None


class TeamInviteRequest(BaseModel):
    email: EmailStr
    role: Literal["member", "admin"] | None = None


class TeamInvite(BaseModel):
    id: str
    """
    Prefixed invite id (inv_<uuid>)
    """
    owner_account_id: str
    invitee_email: str
    role: Literal["member", "admin"]
    expires_at: str
    invited_by_account_id: str | None
    accepted_at: str | None
    created_at: str


class TeamMember(BaseModel):
    id: str
    """
    Prefixed membership id (mem_<uuid>)
    """
    owner_account_id: str
    member_account_id: str
    member_email: str
    role: Literal["member", "admin"]
    invited_at: str
    accepted_at: str
    invited_by_account_id: str | None


class TeamAcceptRequest(BaseModel):
    token: constr(min_length=20)


class TeamOwner(BaseModel):
    owner_account_id: str
    role: Literal["member", "admin"]
    membership_id: str
