// scripts/bump-gui-version.mjs — the desktop-client version bump, by field.
//
// The 0.1.45 release replaced every `version = "0.1.44"` line in Cargo.lock: the
// `tracing` crate happened to sit at 0.1.44 and was pinned to a version that does not
// exist, while the app's own entry (stale at 0.1.36 since that release — no later bump
// had matched it) stayed untouched. All three release builds failed at dependency
// resolution, and the asset-less release became the "latest" release the desktop
// updater fetches its manifest from. These arms run the REAL script on a temp copy of
// the four files and pin that each edit is scoped to the field that names the app —
// so a same-numbered crate is left alone and a stale app entry is corrected — and
// that one refusal writes nothing.

import { execFileSync } from 'node:child_process';
import { mkdirSync, mkdtempSync, readFileSync, rmSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { afterEach, describe, expect, it } from 'vitest';

const HERE = dirname(fileURLToPath(import.meta.url));
const REPO_ROOT = resolve(HERE, '..', '..', '..', '..');
const SCRIPT = resolve(REPO_ROOT, 'scripts/bump-gui-version.mjs');

const PACKAGE_JSON = `{
  "name": "@driftstack/gui-client",
  "private": true,
  "version": "0.1.44",
  "type": "module",
  "engines": {
    "version": "0.1.44"
  }
}
`;
const TAURI_CONF = `{
  "$schema": "https://schema.tauri.app/config/2",
  "productName": "Driftstack",
  "version": "0.1.44",
  "identifier": "dev.driftstack.gui"
}
`;
const CARGO_TOML = `[package]
name = "driftstack-gui"
version = "0.1.44"
edition = "2021"

[dependencies]
tracing = { version = "0.1.44" }
serde = "1"
`;
// The exact shape that broke 0.1.45: a crate at the SAME number as the outgoing
// version, and the app entry stale at an older number.
const CARGO_LOCK = `# This file is automatically @generated by Cargo.
version = 4

[[package]]
name = "driftstack-gui"
version = "0.1.36"
dependencies = [
 "tracing",
]

[[package]]
name = "tracing"
version = "0.1.44"
source = "registry+https://github.com/rust-lang/crates.io-index"
checksum = "8df9b6e13f2d32c91b9bd719c00d1958837bc7dec474d94952798cc8e69eeec3"
`;

let root: string | null = null;

function fixture(overrides: Partial<Record<string, string>> = {}): string {
  root = mkdtempSync(join(tmpdir(), 'bump-gui-'));
  const gui = join(root, 'apps', 'gui-client');
  mkdirSync(join(gui, 'src-tauri'), { recursive: true });
  const files: Record<string, string> = {
    'package.json': PACKAGE_JSON,
    'src-tauri/tauri.conf.json': TAURI_CONF,
    'src-tauri/Cargo.toml': CARGO_TOML,
    'src-tauri/Cargo.lock': CARGO_LOCK,
    ...overrides,
  };
  for (const [rel, text] of Object.entries(files)) writeFileSync(join(gui, rel), text);
  return root;
}

function run(args: string[]): { status: number; stdout: string; stderr: string } {
  try {
    const stdout = execFileSync(process.execPath, [SCRIPT, ...args], {
      encoding: 'utf8',
      stdio: 'pipe',
    });
    return { status: 0, stdout, stderr: '' };
  } catch (err) {
    const e = err as { status?: number; stdout?: string; stderr?: string };
    return { status: e.status ?? -1, stdout: e.stdout ?? '', stderr: e.stderr ?? '' };
  }
}

function read(rel: string): string {
  if (root === null) throw new Error('no fixture');
  return readFileSync(join(root, 'apps', 'gui-client', rel), 'utf8');
}

afterEach(() => {
  if (root !== null) rmSync(root, { recursive: true, force: true });
  root = null;
});

describe('scripts/bump-gui-version.mjs — a by-field desktop-client version bump', () => {
  it('bumps the four files by field: the crate at the outgoing number is untouched and the stale app entry is corrected (the 0.1.45 shape)', () => {
    const r = run(['0.1.45', '--root', fixture(), '--no-validate']);
    expect(r.status, r.stderr).toBe(0);
    // package.json — only the top-level key; the nested one at deeper indent stays.
    expect(read('package.json')).toContain('\n  "version": "0.1.45",');
    expect(read('package.json')).toContain('\n    "version": "0.1.44"');
    expect(read('src-tauri/tauri.conf.json')).toContain('"version": "0.1.45"');
    expect(read('src-tauri/tauri.conf.json')).not.toContain('0.1.44');
    // Cargo.toml — the [package] version only; the dependency at the same number stays.
    const toml = read('src-tauri/Cargo.toml');
    expect(toml).toContain('[package]\nname = "driftstack-gui"\nversion = "0.1.45"');
    expect(toml).toContain('tracing = { version = "0.1.44" }');
    // Cargo.lock — the app entry (stale at 0.1.36) becomes 0.1.45; tracing stays 0.1.44.
    const lock = read('src-tauri/Cargo.lock');
    expect(lock).toContain('[[package]]\nname = "driftstack-gui"\nversion = "0.1.45"\n');
    expect(lock).toContain('[[package]]\nname = "tracing"\nversion = "0.1.44"\n');
    expect(lock).not.toContain('0.1.36');
    expect(lock.match(/0\.1\.45/g)?.length).toBe(1);
  });

  it('refuses a non-version argument and writes nothing', () => {
    const r = run(['0.1', '--root', fixture(), '--no-validate']);
    expect(r.status).toBe(1);
    expect(r.stderr).toMatch(/not a version/);
    expect(read('src-tauri/Cargo.lock')).toBe(CARGO_LOCK);
    expect(read('package.json')).toBe(PACKAGE_JSON);
  });

  it('refuses when a file has no scoped match (a Cargo.lock without the app entry) and writes NONE of the four — one refusal is atomic', () => {
    const lockWithoutApp = CARGO_LOCK.replace('name = "driftstack-gui"', 'name = "something-else"');
    const r = run([
      '0.1.45',
      '--root',
      fixture({ 'src-tauri/Cargo.lock': lockWithoutApp }),
      '--no-validate',
    ]);
    expect(r.status).toBe(1);
    expect(r.stderr).toMatch(
      /Cargo\.lock \[\[package\]\] driftstack-gui: expected exactly one match, found 0/,
    );
    // package.json was resolvable, but nothing may be written when a sibling refuses.
    expect(read('package.json')).toBe(PACKAGE_JSON);
    expect(read('src-tauri/tauri.conf.json')).toBe(TAURI_CONF);
    expect(read('src-tauri/Cargo.toml')).toBe(CARGO_TOML);
    expect(read('src-tauri/Cargo.lock')).toBe(lockWithoutApp);
  });

  it('refuses a Cargo.toml whose [package] section has two version lines (ambiguous — never guess which)', () => {
    const twoVersions = CARGO_TOML.replace(
      'edition = "2021"',
      'edition = "2021"\nversion = "9.9.9"',
    );
    const r = run([
      '0.1.45',
      '--root',
      fixture({ 'src-tauri/Cargo.toml': twoVersions }),
      '--no-validate',
    ]);
    expect(r.status).toBe(1);
    expect(r.stderr).toMatch(
      /Cargo\.toml \[package\] version: expected exactly one match, found 2/,
    );
  });

  it('is usable without arguments only as a usage message (exit 2)', () => {
    const r = run(['--root', fixture(), '--no-validate']);
    expect(r.status).toBe(2);
    expect(r.stderr).toMatch(/usage: bump-gui-version\.mjs <x\.y\.z>/);
  });
});
