// v2-#16 — Postmark transactional email template attribution sweep.
//
// V-205 attribution policy applies to customer-visible copy, not
// just commit messages: every outbound email is customer-facing
// surface and MUST NOT carry AI-tooling watermarks (Claude /
// Anthropic / GPT / Copilot / claude.ai), with the SOLE exception
// of the BYOK Anthropic key rotation reminder which legitimately
// references the customer's own Anthropic API key + console URL.
//
// Also pins the capitalisation convention from the v2-#16 audit
// queue: customer-visible "Driftstack" never appears lowercase in
// email body text. (Lowercase IS allowed in URLs / identifiers
// like driftstack.dev / docs.driftstack.dev / @driftstack.dev.)

import { readFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, resolve } from 'node:path';
import { describe, expect, it } from 'vitest';

const HERE = dirname(fileURLToPath(import.meta.url));
const REPO_ROOT = resolve(HERE, '..', '..', '..', '..');
const EMAIL_SVC = resolve(REPO_ROOT, 'apps/server/src/services/email.ts');

const FORBIDDEN_AI_WATERMARKS = [
  /\bClaude\b/g,
  /\bGPT-?\d?\b/gi,
  /\bCopilot\b/gi,
  /\bgenerated by AI\b/gi,
  /\bwritten by AI\b/gi,
  /\bAI-generated\b/gi,
  /\bclaude\.ai\b/gi,
];

const ALLOWED_ANTHROPIC_CONTEXTS = [
  // BYOK key rotation reminder legitimately references the customer's
  // own Anthropic API key + console URL.
  /Anthropic API key/g,
  /Anthropic console/g,
  /console\.anthropic\.com/g,
  // Function name, type name, comment context — these don't appear
  // in the customer-visible email body, only in the source file.
  /BYOKAnthropic/g,
  /sendByokAnthropic/g,
  /byok-anthropic/g,
  /v2-#11\.5 — BYOK Anthropic/g,
  /\bAnthropic API\b/g,
  // Inline source comments mentioning Anthropic for engineer context
  // (e.g. "Anthropic keys are sensitive"). These are NOT in customer
  // wire copy — the test strips Postmark-emitted strings and these
  // are in comment surface only.
  /No prefix shown — Anthropic/g,
  /provider name \(Anthropic\)/g,
  /Anthropic keys are sensitive/g,
];

describe('v2-#16 email-templates V-205 attribution sweep', () => {
  const body = readFileSync(EMAIL_SVC, 'utf8');

  it('email service file has no Claude / GPT / Copilot / AI-watermark string', () => {
    for (const re of FORBIDDEN_AI_WATERMARKS) {
      const matches = Array.from(body.matchAll(re));
      expect(
        matches.length,
        `V-205 violation: ${re.source} appeared ${matches.length} times in email.ts`,
      ).toBe(0);
    }
  });

  it('only allowed contexts mention "Anthropic" (BYOK reminder + identifiers)', () => {
    // Find every Anthropic mention; remove the allowed contexts;
    // any remainder is a V-205 candidate.
    let scrubbed = body;
    for (const re of ALLOWED_ANTHROPIC_CONTEXTS) {
      scrubbed = scrubbed.replace(re, '');
    }
    const stray = Array.from(scrubbed.matchAll(/\bAnthropic\b/g));
    expect(
      stray.length,
      `Unexpected Anthropic mention(s) in email.ts: ${stray.map((m) => m[0]).join(', ')}`,
    ).toBe(0);
  });

  it('customer-visible Driftstack uses TitleCase in body strings (not "driftstack" lowercase)', () => {
    // Look at every backtick-quoted string + double-quoted string
    // that contains "driftstack" lowercase. Allow URLs only —
    // anything like "your driftstack account" or "the driftstack API"
    // would trip.
    const stringLiterals = Array.from(body.matchAll(/(?:`[^`]+`|"[^"]+"|'[^']+')/g), (m) => m[0]);
    for (const lit of stringLiterals) {
      // Strip URL-looking driftstack tokens (driftstack.dev, etc.).
      const naked = lit.replace(/driftstack\.(dev|com|org|test|io)/g, '');
      const violatesRe = /[\sA-Za-z]driftstack[\s.,'"`?!]/;
      if (violatesRe.test(naked)) {
        // Allow internal identifiers like "DRIFTSTACK_SOCKS5" — these
        // aren't lowercase + don't match this pattern.
        //
        // vacuity-exempt: the condition is the negation of the assertion. This
        // is a find-and-fail loop — the branch is entered only when the literal
        // already violates, and entering it fails. So the arm cannot pass while
        // a violation exists, which is the property
        // `a-test-arm-may-not-hide-all-its-assertions` checks for; it is
        // structurally identical to a hidden assertion and semantically its
        // opposite.
        expect(naked, `lowercase "driftstack" in customer copy: ${lit}`).not.toMatch(violatesRe);
      }
    }
  });

  it('every Driftstack signature line uses em-dash "— Driftstack" (consistent voice)', () => {
    // Pin the sign-off convention. Drift to "- Driftstack" or
    // "Driftstack" alone would inconsistently brand outbound mail.
    const signatures = Array.from(body.matchAll(/— Driftstack[^a-z]/g));
    // At least one signature should exist (we ship multiple emails).
    expect(signatures.length).toBeGreaterThanOrEqual(5);
  });
});
