// W622 — drift guard for sdk-python generated artefacts (3 files):
//  - openapi.json: 14973-line frozen OpenAPI 3.1 spec snapshot used by
//    datamodel-codegen to regenerate Pydantic models.
//  - _generated/__init__.py: codegen-output marker docstring.
//  - _generated/models.py: Pydantic v2 BaseModel set derived from the spec
//    (W140 added AgentIntent5/AgentIntent6 for the scroll + behavioral_pause
//    decomposer intents).

import { existsSync, readFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, resolve } from 'node:path';
import { describe, expect, it } from 'vitest';

const HERE = dirname(fileURLToPath(import.meta.url));
const REPO_ROOT = resolve(HERE, '..', '..', '..', '..');

function read(rel: string): string {
  return readFileSync(resolve(REPO_ROOT, rel), 'utf8');
}

describe('W622 sdk-python generated + openapi content parity', () => {
  it('openapi.json: OpenAPI 3.1.0 + Driftstack API title + 0.0.1 version + V-326e Team-RBAC X-Driftstack-Account header info-doc + MIT license + member-vs-admin scope split + 18-endpoint sample (sessions/api-keys/usage/team/admin) pinned', () => {
    const body = read('packages/sdk-python/openapi.json');
    expect(body).toMatch(/"openapi": "3\.1\.0"/);
    expect(body).toMatch(/"title": "Driftstack API"/);
    expect(body).toMatch(/"version": "0\.0\.1"/);
    expect(body).toMatch(/Driftstack API for iPhone Safari automation\./);
    expect(body).toMatch(/Versioned public contract under \/v1\./);
    expect(body).not.toMatch(/pre-launch|subject to change/i);
    expect(body).toMatch(/## Team RBAC: X-Driftstack-Account header \(V-326e\)/);
    expect(body).toMatch(
      /Members of a team can scope any \/v1\/\* request to the OWNER's resources/,
    );
    expect(body).toMatch(
      /passing\\n`X-Driftstack-Account: acc_<owner-uuid>` request header|passing\\nthe `X-Driftstack-Account: acc_<owner-uuid>` request header/,
    );
    expect(body).toMatch(/Read endpoints \(GET\): both `member` and `admin` roles allowed\./);
    expect(body).toMatch(
      /Write endpoints \(POST \/ PATCH \/ DELETE \/ api-keys rotate\): `admin` role only/,
    );
    expect(body).toMatch(
      /Endpoints that do NOT honor the header: \/v1\/team\/\*, \/v1\/account\/me/,
    );
    expect(body).toMatch(/"name": "MIT"/);
    expect(body).toMatch(/"\/v1\/sessions": \{/);
    expect(body).toMatch(/"\/v1\/sessions\/\{id\}\/navigate": \{/);
    expect(body).toMatch(/"\/v1\/sessions\/\{id\}\/interact": \{/);
    expect(body).toMatch(/"\/v1\/sessions\/\{id\}\/wait": \{/);
    expect(body).toMatch(/"\/v1\/sessions\/\{id\}\/state": \{/);
    expect(body).toMatch(/"\/v1\/sessions\/\{id\}\/capture": \{/);
    expect(body).toMatch(/"\/v1\/api-keys": \{/);
    expect(body).toMatch(/"\/v1\/api-keys\/\{id\}\/rotate": \{/);
    expect(body).toMatch(/"\/v1\/usage": \{/);
    expect(body).toMatch(/"\/v1\/usage\/series": \{/);
    expect(body).toMatch(/"\/v1\/team\/invites": \{/);
    expect(body).toMatch(/"\/v1\/team\/invites\/accept": \{/);
    expect(body).toMatch(/"\/v1\/team\/members": \{/);
    expect(body).toMatch(/"\/v1\/team\/owners": \{/);
    expect(body).toMatch(/"\/v1\/admin\/accounts\/\{id\}\/tier": \{/);
    expect(body).toMatch(/"\/v1\/admin\/accounts\/\{id\}\/suspend": \{/);
    expect(body).toMatch(/"\/v1\/admin\/accounts\/\{id\}\/unsuspend": \{/);
    expect(body).toMatch(/"webhooks": \{\}/);
    expect(existsSync(resolve(REPO_ROOT, 'packages/sdk-python/openapi.json'))).toBe(true);
  });

  it('_generated/__init__.py: codegen-output marker + scripts/generate.sh regen reference + hand-edit-nothing warning + driftstack-package-root re-export note pinned', () => {
    const body = read('packages/sdk-python/src/driftstack/_generated/__init__.py');
    expect(body).toMatch(/^"""Codegen output\. Regenerated by ``scripts\/generate\.sh``\.$/m);
    expect(body).toMatch(
      /Hand-edit nothing in this package — it gets clobbered every regeneration\./,
    );
    expect(body).toMatch(
      /Customer-facing types are re-exported from :mod:`driftstack` \(the package/,
    );
    expect(body).toMatch(/root\); to add a wrapping layer, edit there\./);
    expect(
      existsSync(resolve(REPO_ROOT, 'packages/sdk-python/src/driftstack/_generated/__init__.py')),
    ).toBe(true);
  });

  it('_generated/models.py: datamodel-codegen filename=openapi.json + Pydantic AnyUrl/AwareDatetime/BaseModel/EmailStr/Field/RootModel/conint/constr imports (multi-line) + 8-value account_tier Literal + account_status 3-value + 30+ core BaseModels (Account/Team/AccountMeResponse/UpdateAccountMeRequest/ApiKey/Session/SessionState/Problem/Quotas/UsagePeriodSummary/CreateSessionRequest/CreateApiKeyResponse/WebhookEndpoint/WebhookDelivery/AdminAuditLogEntry/RotateApiKeyResponse/TeamInvite/TeamMember/TeamAcceptRequest/TeamOwner) pinned', () => {
    const body = read('packages/sdk-python/src/driftstack/_generated/models.py');
    expect(body).toMatch(/^# generated by datamodel-codegen:$/m);
    expect(body).toMatch(/^#\s+filename:\s+openapi\.json$/m);
    expect(body).toMatch(/^from __future__ import annotations$/m);
    expect(body).toMatch(/from typing import Any, Literal/);
    expect(body).toMatch(/from uuid import UUID/);
    // Regenerated 2026-05-31: the AgentSession / Recipe / AgentIntent /
    // IntentResult schemas grew the import list past the line cap → multi-line
    // parenthesized form, and added RootModel for the discriminated-union
    // RootModel types. Discrete pins (no long backtracking chain).
    expect(body).toMatch(/from pydantic import \(/);
    expect(body).toMatch(/^\s+AnyUrl,$/m);
    expect(body).toMatch(/^\s+AwareDatetime,$/m);
    expect(body).toMatch(/^\s+RootModel,$/m);
    expect(body).toMatch(/^\s+constr,$/m);
    expect(body).toMatch(/^class Account\(BaseModel\):$/m);
    expect(body).toMatch(/id: constr\(/);
    expect(body).toMatch(
      /pattern=r"\^acc_\[0-9a-f\]\{8\}-\[0-9a-f\]\{4\}-\[0-9a-f\]\{4\}-\[0-9a-f\]\{4\}-\[0-9a-f\]\{12\}\$"/,
    );
    expect(body).toMatch(/email: EmailStr/);
    expect(body).toMatch(/tier: Literal\[/);
    expect(body).toMatch(/^\s+"free",$/m);
    expect(body).toMatch(/^\s+"solo_manual",$/m);
    expect(body).toMatch(/^\s+"team_manual",$/m);
    expect(body).toMatch(/^\s+"agency_manual",$/m);
    expect(body).toMatch(/^\s+"api_starter",$/m);
    expect(body).toMatch(/^\s+"api_builder",$/m);
    expect(body).toMatch(/^\s+"api_scale",$/m);
    expect(body).toMatch(/^\s+"enterprise",$/m);
    expect(body).toMatch(/status: Literal\["active", "suspended", "deleted"\]/);
    expect(body).toMatch(/created_at: AwareDatetime/);
    expect(body).toMatch(/ISO 8601 timestamp with timezone offset, e\.g\. 2026-05-02T09:15:00Z/);
    expect(body).toMatch(/^class Team\(BaseModel\):$/m);
    expect(body).toMatch(/role: Literal\["admin", "member"\]/);
    expect(body).toMatch(/^class AccountMeResponse\(BaseModel\):$/m);
    expect(body).toMatch(/region: Literal\["us", "eu", "apac"\] \| None/);
    expect(body).toMatch(/avatar_source: Literal\["user", "idp", "none"\]/);
    expect(body.match(/timeoutMs: conint\(ge=0\) \| None = None/g)).toHaveLength(5);
    expect(body).toMatch(/mfa_enrolled: bool/);
    expect(body).toMatch(/concurrent_session_cap: conint\(ge=0\)/);
    expect(body).toMatch(/profile_count: conint\(ge=0\)/);
    expect(body).toMatch(/teams: list\[Team\]/);
    expect(body).toMatch(/^class UpdateAccountMeRequest\(BaseModel\):$/m);
    expect(body).toMatch(/^class ApiKey\(BaseModel\):$/m);
    expect(body).toMatch(/^class Session\(BaseModel\):$/m);
    expect(body).toMatch(/^class SessionState\(BaseModel\):$/m);
    expect(body).toMatch(/^class Problem\(BaseModel\):$/m);
    expect(body).toMatch(/^class Quotas\(BaseModel\):$/m);
    expect(body).toMatch(/^class UsagePeriodSummary\(BaseModel\):$/m);
    expect(body).toMatch(/^class CreateSessionRequest\(BaseModel\):$/m);
    expect(body).toMatch(/^class CreateSessionResponse\(BaseModel\):$/m);
    expect(body).toMatch(/^class NavigateRequest\(BaseModel\):$/m);
    expect(body).toMatch(/^class InteractRequest\(BaseModel\):$/m);
    expect(body).toMatch(/^class WaitRequest\(BaseModel\):$/m);
    expect(body).toMatch(/^class CaptureRequest\(BaseModel\):$/m);
    expect(body).toMatch(/^class CreateApiKeyRequest\(BaseModel\):$/m);
    expect(body).toMatch(/^class CreateApiKeyResponse\(BaseModel\):$/m);
    expect(body).toMatch(/^class WebhookEndpoint\(BaseModel\):$/m);
    expect(body).toMatch(/^class CreateWebhookRequest\(BaseModel\):$/m);
    expect(body).toMatch(/^class WebhookDelivery\(BaseModel\):$/m);
    expect(body).toMatch(/^class AdminAccount\(BaseModel\):$/m);
    expect(body).toMatch(/^class AdminAuditLogEntry\(BaseModel\):$/m);
    expect(body).toMatch(/^class RotateApiKeyResponse\(BaseModel\):$/m);
    expect(body).toMatch(/^class RotateApiKeyRequest\(BaseModel\):$/m);
    expect(body).toMatch(/^class TeamInviteRequest\(BaseModel\):$/m);
    expect(body).toMatch(/^class TeamInvite\(BaseModel\):$/m);
    expect(body).toMatch(/Prefixed invite id \(inv_<uuid>\)/);
    expect(body).toMatch(/^class TeamMember\(BaseModel\):$/m);
    expect(body).toMatch(/Prefixed membership id \(mem_<uuid>\)/);
    expect(body).toMatch(/^class TeamAcceptRequest\(BaseModel\):$/m);
    expect(body).toMatch(/token: constr\(min_length=20\)/);
    expect(body).toMatch(/^class TeamOwner\(BaseModel\):$/m);
    // W140 — the AgentIntent discriminated union exposes scroll + behavioral_pause
    // in the python SDK (AgentIntent5/AgentIntent6 generated from the openapi spec).
    expect(body).toMatch(/^\s+kind: Literal\["scroll"\]$/m);
    expect(body).toMatch(/^\s+direction: Literal\["up", "down"\]$/m);
    expect(body).toMatch(/^\s+amount_px: PositiveInt \| None = None$/m);
    expect(body).toMatch(/^\s+kind: Literal\["behavioral_pause"\]$/m);
    expect(body).toMatch(/^\s+reading_word_count: conint\(ge=0\) \| None = None$/m);
    expect(
      existsSync(resolve(REPO_ROOT, 'packages/sdk-python/src/driftstack/_generated/models.py')),
    ).toBe(true);
  });
});
