// GUI audit #13 — the app's native commands have an access list.
//
// Tauri checks an APP command against the capability files only once the app
// declares an app manifest; without one, any page loaded in a window the Rust
// label check accepts — a remote page included, if a window were ever navigated
// to one — could call `secret_load` and read the account key. Declaring every
// command here generates `allow-<command>` / `deny-<command>` permissions
// (permissions/autogenerated/), and each capability grants exactly the commands
// its windows call. Capabilities apply to the app's own local origin only.
//
// ⚠️ A command added to `generate_handler!` in src/lib.rs must be added here AND
// granted in the capability of every window that calls it, or it is refused at
// runtime. tests/unit/a-page-in-the-app-window-can-reach-only-the-native-
// commands-granted-to-it.test.ts pins both.
const APP_COMMANDS: &[&str] = &[
    "ping",
    "secret_save",
    "secret_load",
    "secret_delete",
    "simulator_control_key_load",
    "simulator_control_key_delete",
    "proxy_test",
    "proxy_exit_probe",
    "endpoint_resolve",
    "simulator_app_supported",
    "launch_simulator",
    "close_simulator_windows",
    "mark_session_download",
    "repair_simulator_install",
    "set_dock_tile",
    "reset_dock_tile",
];

fn main() {
    tauri_build::try_build(
        tauri_build::Attributes::new()
            .app_manifest(tauri_build::AppManifest::new().commands(APP_COMMANDS)),
    )
    .expect("failed to run tauri-build");
}
