#!/usr/bin/env bash
# Re-generate Pydantic models from the OpenAPI spec.
#
# Prereqs:
#   - openapi.json present (run `npm run sdk:python:dump-spec` from repo root)
#   - venv set up: python3.10 -m venv .venv && .venv/bin/pip install -e '.[dev]'
#
# This script is idempotent — running it overwrites _generated/models.py
# with the latest spec. Hand-edit nothing there; if a tweak is needed,
# wrap the generated type from the customer-facing surface.

set -euo pipefail

HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
SPEC="${HERE}/openapi.json"
OUT="${HERE}/src/driftstack/_generated/models.py"

if [[ ! -f "$SPEC" ]]; then
  echo "[generate] missing $SPEC" >&2
  echo "[generate] run 'npm run sdk:python:dump-spec' from the repo root first" >&2
  exit 1
fi

mkdir -p "$(dirname "$OUT")"

"${HERE}/.venv/bin/datamodel-codegen" \
  --input "$SPEC" \
  --input-file-type openapi \
  --output "$OUT" \
  --output-model-type pydantic_v2.BaseModel \
  --target-python-version 3.10 \
  --use-schema-description \
  --use-field-description \
  --use-double-quotes \
  --enum-field-as-literal all \
  --use-standard-collections \
  --use-union-operator

# Mark the generated package as importable.
INIT="$(dirname "$OUT")/__init__.py"
cat >"$INIT" <<'EOF'
"""Codegen output. Regenerated by ``scripts/generate.sh``.

Hand-edit nothing in this package — it gets clobbered every regeneration.
Customer-facing types are re-exported from :mod:`driftstack` (the package
root); to add a wrapping layer, edit there.
"""
EOF

echo "[generate] wrote $OUT"
